source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking'
pod 'ZBUtilities'
pod 'HockeySDK'
pod 'ZBarSDK', '~> 1.3.1'
pod 'SDWebImage'
pod 'libPhoneNumber-iOS', '~> 0.7.3'
