source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking'
pod 'ZBUtilities'
pod 'ZBarSDK', '~> 1.3.1'
pod 'SDWebImage'
pod 'libPhoneNumber-iOS', '~> 0.7.3'
pod 'HMSegmentedControl', '~> 1.4.0'
pod 'hpple', '~> 0.2.0'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'FTCoreText', '~> 1.0.1'
